---
:concurrency: 25
:pidfile: ./tmp/pids/sidekiq.pid
:logfile: ./log/sidekiq_development.log
development:
  :concurence: 10
staging:
  :concurrency: 10
production:
  :concurrency: 20
:queues:
  - [mailers, 5]
